#!/bin/sh
APPDIR=`dirname $0`;
java -XstartOnFirstThread -Dgwt.args="-web -out www-test" -Xmx256M -cp "$APPDIR/src:$APPDIR/test:$APPDIR/war/WEB-INF/classes:/Applications/eclipse/plugins/org.junit4_4.5.0.v20090824/junit.jar:/Applications/eclipse/plugins/com.google.gwt.eclipse.sdkbundle.macosx_1.7.1.v200909221731/gwt-mac-1.7.1/gwt-user.jar:/Applications/eclipse/plugins/com.google.gwt.eclipse.sdkbundle.macosx_1.7.1.v200909221731/gwt-mac-1.7.1/gwt-dev-mac.jar" junit.textui.TestRunner com.esial.richercms.client.RichercmsTest "$@";
